
#I likes me makefiles like I likes me women: SILENT!
.SILENT:

BASEDIR = ..
SRCDIR = $(BASEDIR)/src
#GMPDIR = $(BASEDIR)/../gmp

VPATH = $(SRCDIR)

INCLUDES =  -I$(BASEDIR)/src -I$(BASEDIR)/include

CPP = g++

COMPLIB = SSI.a

ifdef DEBUG
CPPFLAGS = -g $(INCLUDES)
else
CPPFLAGS = -O2 $(INCLUDES)
endif

.cpp.o:
	echo $<
	$(CPP) $(CPPFLAGS) -c $<
	


SRC = \
	Anomaly.cpp \
	Block.cpp \
	Character.cpp \
	Expression.cpp \
	HelperFuncs.cpp \
	Interface.cpp \
	Interpreter.cpp \
	LanguageConstants.cpp \
	List.cpp \
	Operator.cpp \
	ParserAnomaly.cpp \
	Scope.cpp \
	ScopeObject.cpp \
	ScopeObjectVisitor.cpp \
	ScriptFile.cpp \
	Slib-Common.cpp \
	Slib-Math.cpp \
	Slib-Time.cpp \
	SpecialVars.cpp \
	Unicode.cpp \
	Variable.cpp \
	VersionInfo.cpp \
	Word.cpp
	
OBJ=$(SRC:.cpp=.o)


all: pantson $(SRC) $(OBJ) $(COMPLIB)
	echo All done.  Have a nice day!

$(COMPLIB):
	echo Linking $(COMPLIB)...
	ar rc $(COMPLIB) $(OBJ)
	cp SSI.a $(BASEDIR)/bin/SSI.a

clean:
	rm -f *.o $(COMPLIB)
	echo "    Mr. Clean gets rid of dirt and grime and grease in just a minute,"
	echo "    Mr. Clean will clean your whole house and everything in it."
	echo 

backup:
	cd ..;perl MakeBackup.pl
	
pantson:
	echo Using flags "$(CPPFLAGS)"
	echo Compiling, keep your pants on...
	
	
