##This is pretty much ripped off from the VLC source code.  So thanks to them.

if test -z "${srcdir}"; then
    srcdir="`sed -ne 's/^srcdir *= *//p' < Makefile`"
fi
if test -z "${builddir}"; then
builddir="`sed -ne 's/^top_builddir *= *//p' < Makefile`"
fi


file="./SVNRevision.cpp"
if which svnversion 2>&1 >/dev/null; then
CHANGESET=`svnversion $srcdir`
else
CHANGESET='exported'
fi

rm -f ${file}.tmp
cat > ${file}.tmp << EOF
/*
DO NOT EDIT THIS FILE - IT IS REGENERATED AT EVERY COMPILE
*/

#include "Unicode.hpp"

namespace SS{
const SS::CHAR* SSI_SVNRevision = "${CHANGESET}";
}
EOF
if diff >/dev/null 2>&1 ${file} ${file}.tmp
then
rm -f ${file}.tmp
else
echo "creating new ${file}"
mv -f ${file}.tmp ${file}
fi
