/*
Copyright (c) 2004-2005 Daniel Jones (DanielCJones@gmail.com)

This is part of the  StoryScript (AKA: SS, S^2, SSqared, etc) software.  Full license information is included in the file in the top directory named "license".

NOTES: Just some quick defines for keeping track of the version.
	My version system changes every few weeks it seems, but here's
	what I use now:
	
	SSI_VERSION denotes the major revision.  This is incremented when
	I have made significant modifications to the language that seem to
	be stable.  I also give each major version a nickname.  For version
	0 it is "Chernobyl".  Don't ask me why.
	
	SSI_PLATFORM should say windows or linux (posix).
	
	SSI_LASTCOMPILE is the date and time of the last full compile.

*/

#if !defined(SS_VersionInfo)
#define SS_VersionInfo


#include "Unicode.hpp"
#include "Defines.hpp"

namespace SS
{

extern const SS_API SS::Char* SSI_MAJORVERSION;

extern const SS_API SS::Char* SSI_PLATFORM;

extern const SS_API SS::Char* SSI_COMPILEDATE;

//This is set in the file SVNRevision.cpp, which is generated by the makefile.
extern const SS_API SS::Char* SSI_SVNRevision;

SS_API const SS::Char* GetVersionString();


}




#endif

