import glob

env = Environment( CCFLAGS='-O2' )
conf = Configure(env)
env = conf.Finish()

src = Split("""
	src/Console.cpp
	src/ConsoleInterface.cpp
	src/main.cpp
	""")

#Main Program
SSIConsole = env.Program( 'storyscript', src, CPPPATH = ['include', '../ssi/include'], LIBS=['storyscript', 'curses'])
#BinCopy = env.Install( './bin', SSIConsole )
env.Alias( 'MainBuild', [SSIConsole] )

Default( 'MainBuild' )

#Install
env.InstallAs('/usr/bin/storyscript', SSIConsole )
env.Alias( 'install', '/usr/bin/storyscript' )
